name: rpmsign
description: A GitHub Action to sign RPM packages using passphrase protected GPG keys.
branding:
  icon: pen-tool
  color: blue

inputs:
  gpg_private_key:
    description: GPG private key to be used to sign, in armor protected format.
    required: true
  gpg_private_key_password:
    description: Passphrase to use to sign with this private key.
    required: true
  gpg_name:
    description: Name to use to sign.
    required: true
  rpm_file:
    description: A single rpm to be signed.
    required: false
    default: '##'
  rpm_folder:
    description: Folder with rpm files to be signed.
    required: false
    default: '##'
  output_folder:
    description: Folder where signed rpm files must be placed.
    required: false
    default: 'signed_packages'

runs:
  using: 'docker'
  image: 'docker://dantesignal31/rpmsign:latest'

  args:
    - -k "${{ inputs.gpg_private_key }}"
    - -p ${{ inputs.gpg_private_key_password }}
    - -n $"{{ inputs.gpg_name }}"
    - -s${{ inputs.rpm_file }}
    - -f ${{ inputs.rpm_folder }}
    - -o ${{ inputs.output_folder }}
